export const ADD_APPARTMENTS = 'ADD_APPARTMENTS';
export const SORT_APARTMENTS = 'SORT_APARTMENTS';
export const ADD_USER_DATA = 'ADD_USER_DATA';
export const REVERSE_ORDER = 'REVERSE_OTHER';
export const UPDATE_SIMILAR_APARTMENTS = 'UPDATE_SIMILAR_APARTMENTS';
